Avoid passing address of member in packed struct #1074
zeek/zeek pull request #1153
Opened 2020-09-01 18:38 UTC by ckreibich

This appeases -Waddress-of-packed-member warnings in some
compiler/platform combinations by offering reference-based
alternatives to CopyIPv4/CopyIPv6 (for symmetry).

2020-09-02 20:45 UTC, jsiwek requested changes
A series of observations:

- For the proposed `CopyIPv{4,6}()` overloads, taking a const-reference argument
  and then casting away `const` in order to modify it is misleading.  Also
  skeptical that a pointer versus reference truly has different meaning in
  terms of underlying alignment properties since a reference is still
  essentially a pointer and a compiler might just as well warn against
  binding a reference to packed fields (due to same issue of possible misalignment).
  Reading into https://reviews.llvm.org/D20561, seems like that
  packed-member-reference-binding diagnostic may have also been originally
  intended, but possibly still a planned addition.

- Since `CopyIPv4()` is implemented via `memcpy()`, I don't think
  (mis)alignment matters in terms of the local effects: it should be equivalent
  to copying byte-by-byte from memory locations and so would be resilient to
  receiving an argument that's unaligned.

- Are the `ip_src`/`ip_dst` members of the particular `struct ip` used in
  `PIA_TCP::FirstPacket()` guaranteed to be aligned?  No, I don't think so,
  since the struct is overlaid on top of `static char dummy_packet[]` and
  I've read there's no alignment guarantee for that
  (i.e. since `char` size/alignment requirement is 1 byte).
  Is that a problem?  Assuming some later code does do an unaligned access,
  the result depends on architecture: it either has correct behavior with
  performance overhead or just incorrect behavior.

- Can we do something to guarantee alignment of those members?  Should
  be able to `alignas(4)` the `dummy_packet` memory.  Assuming that
  `struct ip` is correctly defined/packed to be exactly 20 bytes and `ip_src`
  is at byte-offset 12 with size/alignment of 4 bytes, then accesses to those
  members as overlaid within the aligned `dummy_packet` must also be aligned.
  (Reason for thinking `alignas(4)` and not `alignas(in_addr)` is just clarity/generalization
  since the memory block can also be for use w/ accessing TCP header fields, largest of
  which is also 4-bytes)

- Does doing that `alignas()` resolve the `-Waddress-of-packed-member` compiler
  warning?  No.  I don't know why, maybe there's a reason it can't
  determine the alignment statically even though we can (or another
  real possibility is that compiler understands alignment rules better than
  me and there's still an issue even after aligning `dummy_packet`).
  This doesn't seem like a critical path (and might get optimized away anyway),
  so I'd suggest just making a temporary `in_addr` on the stack, `CopyIPv4()`
  into that, then copy back into `ip4->ip_{src,dst}`.

So the suggestion I come up with after all that looks like:

```diff
diff --git a/src/analyzer/protocol/pia/PIA.cc b/src/analyzer/protocol/pia/PIA.cc
index 2e1aa8b94..f898567ce 100644
--- a/src/analyzer/protocol/pia/PIA.cc
+++ b/src/analyzer/protocol/pia/PIA.cc
@@ -206,7 +206,7 @@ void PIA_TCP::Init()

 void PIA_TCP::FirstPacket(bool is_orig, const IP_Hdr* ip)
	{
-	static char dummy_packet[sizeof(struct ip) + sizeof(struct tcphdr)];
+	alignas(4) static char dummy_packet[sizeof(struct ip) + sizeof(struct tcphdr)];
	static struct ip* ip4 = nullptr;
	static struct tcphdr* tcp4 = nullptr;
	static IP_Hdr* ip4_hdr = nullptr;
@@ -230,21 +230,26 @@ void PIA_TCP::FirstPacket(bool is_orig, const IP_Hdr* ip)
			ip4_hdr = new IP_Hdr(ip4, false);
			}

+		in_addr tmp_src;
+		in_addr tmp_dst;
+
		if ( is_orig )
			{
-			Conn()->OrigAddr().CopyIPv4(&ip4->ip_src);
-			Conn()->RespAddr().CopyIPv4(&ip4->ip_dst);
+			Conn()->OrigAddr().CopyIPv4(&tmp_src);
+			Conn()->RespAddr().CopyIPv4(&tmp_dst);
			tcp4->th_sport = htons(Conn()->OrigPort());
			tcp4->th_dport = htons(Conn()->RespPort());
			}
		else
			{
-			Conn()->RespAddr().CopyIPv4(&ip4->ip_src);
-			Conn()->OrigAddr().CopyIPv4(&ip4->ip_dst);
+			Conn()->RespAddr().CopyIPv4(&tmp_src);
+			Conn()->OrigAddr().CopyIPv4(&tmp_dst);
			tcp4->th_sport = htons(Conn()->RespPort());
			tcp4->th_dport = htons(Conn()->OrigPort());
			}

+		ip4->ip_src = tmp_src;
+		ip4->ip_dst = tmp_dst;
		ip = ip4_hdr;
		}

```

2020-09-02 22:53 UTC, ckreibich commented
Oh yikes, I got the copy direction wrong! Of course, the reference shouldn't be const. To clarify the rest of the approach: my thought was that ultimately it's a memcpy that uses the address, and that it takes a `void*`, the alignment concern isn't valid.

Fwiw, I did a bit of research before putting the patch together to see how other projects have addressed the warning. It varies widely, and a local variable is a common work-around — I had just hoped to be able to do without it.

`alignas` is cool, I wasn't ware of it.

Since the compiler only complained about this particular setting, it seems fine to me to also fix it locally. So, no objections from my side Jon. Thanks for the detailed break-down.

2020-09-02 23:08 UTC, ckreibich commented
Patch updated. @jsiwek are we in agreement that `alignas` isn't required, after all?

2020-09-03 04:46 UTC, jsiwek reviewed
Thanks, in terms of just resolving the reported/relevant issue of "compiler warnings (that aren't concerning in light of the `CopyIPv4`  implementation being `memcpy`)", I agree the `alignas` isn't required.  But still may be worth a (separate) issue/fix since other code down the line may end up doing unaligned accesses and result in the same portability concerns.

Anyone else have an opinion on how to handle?

2020-09-11 20:54 UTC, jsiwek approved these changes
Switching my review to "approval" for clarity, but feels like approving myself since I offered such a similar patch, so prefer to leave for another @zeek/mergemaster to complete/merge.

(The question of alignment-hygiene will likely come up in #822 again, so seems fine to punt that as independent issue)

2020-09-17 18:25 UTC, merged