GH-1487: Handle error from ValueToVal instead of ignoring it
zeek/zeek pull request #1488
Opened 2021-04-01 22:40 UTC by timwoj

As discussed in an email thread.

2021-04-02 01:28 UTC, jsiwek requested changes
Thanks, can you fix the leak I mentioned inline and also add a test case?

Also, seems there's some duplication of this code for use in both the Config Framework usage and the Input Framework usage (`src/input/Manager.cc`).   A test case for the Input Framework path is this:

With example input file [denylist.txt](https://github.com/zeek/zeek/files/6247174/denylist.txt)

```zeek
# test.zeek
type Idx: record {
    ip: addr;
};

type Color: enum { Red, White, Blue, };

type Val: record {
    colors: set[Color];
};

global denylist: table[addr] of Val = table();

event zeek_init() {
    Input::add_table([$source="denylist.txt", $name="denylist",
                      $idx=Idx, $val=Val, $destination=denylist]);
    Input::remove("denylist");
}

event Input::end_of_data(name: string, source: string) {
    print denylist;
}
```

```
$ zeek ./test.zeek 
warning: Value 'asdf' for stream 'denylist' is not a valid enum.
Segmentation fault: 11
```

2021-04-02 01:28 UTC, jsiwek commented on src/threading/SerialTypes.cc
> +					return nullptr;
This can leak the `t = new TableVal` allocated just above this loop.  Should be able to simply make `t` an `IntrusivePtr` instead to avoid that.

2021-04-07 18:03 UTC, timwoj commented
I added fixes for the input framework. In looking at that code I think a lot of it could be changed to return IntrusivePtrs instead of raw pointers, but that's probably out of scope for this PR. I'll make a separate issue to track it.

2021-04-08 00:20 UTC, jsiwek requested changes
Thanks, I found a few more things that could be polished and inlined comments for them.  Also a couple more things:

* This assertion seems wrong now (I'd move it a few lines down so it's after the `if ( convert_error )` branch: https://github.com/zeek/zeek/blob/c9874be22af14a6dbf6e75b257bc290074b356e7/src/input/Manager.cc#L1710

* The Config Framework path from the original bug report could still use a test case.  That should look something like this:

```zeek
# test.zeek
@load base/frameworks/config

type Color: enum { Red, Green, Blue, };

option mycolors = set(Red, Green);

event zeek_init()
	{ Config::read_config("configfile"); }

event Input::end_of_data(name: string, source:string)
	{ print mycolors; terminate(); }
```

```
# configfile
mycolors Red,asdf,Blue
```

```
$ zeek -b ./test.zeek
warning: Value 'asdf' for source 'thread configfile/Input::READER_CONFIG' is not a valid enum.
Segmentation fault (core dumped)
```

2021-04-12 21:26 UTC, jsiwek approved these changes
Thanks, I directly pushed the `assert()` tweak I mentioned and going to leave to @0xxon for secondary review.

2021-04-16 08:43 UTC, 0xxon approved these changes

2021-04-16 15:09 UTC, merged