Change SSH version field to be `&optional`.
zeek/zeek pull request #1602
Opened 2021-06-16 11:02 UTC by bbannier

In 3769ed6c668 we added handling for SSH version 1.99 which unsed a SSH
version of 0 to indicate weird cases where no version could be
determined.

This patch is a fixup for that patch. Instead of using a magic version
of 0 we now use an `&optional` version value. If no SSH version can be
extracted the version will be unset; additionally a `conn_weird` event
will be raised.

Closes #1590.

2021-06-16 14:49 UTC, grigorescu reviewed
Looks good to me!

2021-06-16 16:02 UTC, 0xxon requested changes

2021-06-17 07:25 UTC, bbannier commented on scripts/base/protocols/ssh/main.zeek
> +		## `conn_weird` event will be raised.
I expanded this part (also incorporating the changes you asked for below).

2021-06-17 07:27 UTC, bbannier commented on scripts/base/protocols/ssh/main.zeek
> +	Reporter::conn_weird("SSH protocol version mismatch", c, version);
I tried to address this. Now we only raise a `conn_weird` if both client and server versions are set to some non-empty strings, and no shared version can be extracted. I also tweaked the message passed in the weird (let me know if the way I pass up the client and server version strings isn't useful), and used different messages for the different paths.

2021-06-17 09:53 UTC, merged

2021-06-17 09:53 UTC, 0xxon commented
Just FYI - I renamed the weirds during the merge.