Robustness improvements to the input framework's handling of unset fields
zeek/zeek pull request #1605
Opened 2021-06-17 23:00 UTC by ckreibich

This does two things:
- It fixes a segfault that could happen when using unset fields in an input framework input file. For this you had to use a table input stream, index into the receiving table with a tuple, and have an unset-field indicator in your input file. (This came up on Slack the other day.)
- While working on this I noticed that the input framework generally loads unset fields (via `-`) happily, even into records where the corresponding field isn't `&optional`. The danger here is of course that according to the type definition it's safe to access the member, but at runtime Zeek might abort because it doesn't find a value. So the second commit makes the input framework skip entries that would leave fields unset when they're not marked `&optional`. When a field is `&optional`, all works as before.

I'm also updating the corresponding tests a bit to test the new behavior. I'll update the docs if this looks okay to you.

To reproduce the crash:

test.zeek:
```
type Key: record {
        sport: count;
        dport: count;
};

type Val: record {
        name: string;
};

global t: table[count, count] of Val = table();

event zeek_init() {
        Input::add_table([$source="foo.txt", $name="foo",
                          $idx=Key, $val=Val, $destination=t]);
}
```
foo.txt (properly tabbed):
```
#fields sport   dport   name
-       80      foo
```
With current master:
```
$ gdb zeek
...
(gdb) run ./test.zeek
...
Thread 1 "zeek" received signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  zeek::ListVal::Append (this=this@entry=0x4493980, v=...) at /home/christian/devel/zeek/zeek/src/Val.cc:1271
#1  0x00000000009b32e9 in zeek::input::Manager::ValueToIndexVal (this=0x1b0c0c0, i=0x4d8d3a0, num_fields=<optimized out>, type=0x4704d30, vals=0x7fffc8002ee0, have_error=@0x7fffffffc5bb: false)
    at /home/christian/devel/zeek/zeek/src/input/Manager.cc:1080
#2  0x00000000009b3d11 in zeek::input::Manager::SendEntryTable (this=0x1b0c0c0, i=0x4d8d3a0, vals=0x7fffc8002ee0) at /home/christian/devel/zeek/zeek/src/input/Manager.cc:1263
#3  0x00000000009b452e in zeek::input::Manager::SendEntry (this=0x1b0c0c0, reader=<optimized out>, vals=0x7fffc8002ee0) at /home/christian/devel/zeek/zeek/src/input/Manager.cc:1109
#4  0x00000000009b6f38 in zeek::input::SendEntryMessage::Process (this=<optimized out>) at /home/christian/devel/zeek/zeek/src/input/ReaderBackend.cc:85
#5  0x00000000008bb1a3 in zeek::threading::Manager::Flush (this=0xe3b5c0) at /home/christian/devel/zeek/zeek/src/threading/Manager.cc:215
#6  0x00000000008bb398 in zeek::threading::Manager::Terminate (this=0xe3b5c0) at /home/christian/devel/zeek/zeek/src/threading/Manager.cc:47
#7  0x0000000000788b55 in zeek::detail::terminate_bro () at /home/christian/devel/zeek/zeek/src/zeek-setup.cc:324
#8  0x0000000000788ef0 in zeek::detail::cleanup (did_run_loop=<optimized out>) at /home/christian/devel/zeek/zeek/src/zeek-setup.cc:936
#9  0x0000000000672e32 in main (argc=<optimized out>, argv=<optimized out>) at /home/christian/devel/zeek/zeek/src/main.cc:81
```

2021-06-22 10:30 UTC, 0xxon requested changes
This looks great.

We should probably call this out in NEWS pretty prominently - I can see that some people might depend on the old behavior working, and then wondering why their data suddenly does not work anymore. But - it still is a change we should make.

However - it also seems that this basically breaks the empty-values-hashing test - since all the testcases also are error-cases now (which kind of proves the point - even that test depends on the old behavior).

Could you perhaps change that test to make sense again? I assume it just needs a couple of &optionals.

2021-06-25 05:24 UTC, ckreibich commented
Sure thing @0xxon — I've expanded that test to verify a few more combinations and rebased the whole thing on top of master. Let me know your thoughts.

2021-06-30 14:52 UTC, 0xxon approved these changes

2021-07-01 03:03 UTC, ckreibich commented
Just a rebase on top of master, since some time had passed.

2021-07-01 03:52 UTC, merged