Management framework: config validation
zeek/zeek pull request #2172
Opened 2022-06-14 05:52 UTC by ckreibich

This adds a validation stage to the controller that looks for possible misconfigurations when the client uploads a configuration. 

Also I noticed that I overlooked possible collisions in node port auto-assignment, for which this includes a fix, as well as for the corner case of entirely empty configurations.

Finally, this adds two on/off knobs for allowing the stdout/stderr of output coming from nodes to appear on the Supervisor console despite redirection to files, since this allows "docker logs" to show all such output, simplifying test troubleshooting.

2022-06-17 16:30 UTC, timwoj requested changes

2022-06-17 16:30 UTC, timwoj commented on scripts/policy/frameworks/management/controller/main.zeek
> +	# Otherwise, check if we're able to send the config to all agents
This "otherwise" makes me think this this call should either be in an `else` or the above block should have returned. Is that right?

2022-06-21 06:17 UTC, rsmmr approved these changes

2022-06-21 19:25 UTC, timwoj approved these changes

2022-06-22 00:21 UTC, merged