Spelling scripts
zeek/zeek pull request #2503
Opened 2022-10-26 00:01 UTC by jsoref

This is a subset per https://github.com/zeek/zeek/pull/2499#issuecomment-1291179339

2022-10-31 22:11 UTC, timwoj requested changes
Thanks for the shorter version. I had a few comments.

2022-10-31 22:11 UTC, timwoj commented on scripts/base/init-bare.zeek
> +		committed: stable_how_t &optional;	##< TODO.
This is a functional change that should be reverted.

2022-10-31 22:11 UTC, timwoj commented on scripts/base/protocols/smb/const-nt-status.zeek
> +	[0xC0190017] = [$id="TRANSACTION_INVALID_MARSHALL_BUFFER", $desc="The buffer passed into NtPushTransaction or NtPullTransaction is not in a valid format."],
These strings actually come to us from Microsoft and should remain as-is.

2022-10-31 22:11 UTC, timwoj commented on scripts/base/protocols/smb/const-nt-status.zeek
> +	[0xC01E050F] = [$id="GRAPHICS_OPM_SPANNING_MODE_ENABLED", $desc="DxgkDdiOpmCreateProtectedOutput() could not create a protected output because the video present target is in spanning mode."],
These strings actually come to us from Microsoft and should remain as-is.

2022-11-01 01:11 UTC, jsoref commented
The only btest output I got was https://github.com/bazelbuild/bazel/issues/16413

```
% ../../auxil/btest/btest -j $(nproc)

[ 66%] scripts.base.frameworks.logging.rotate-ascii-logdir-leftover-log-rotation-shadow
[ 66%] scripts.base.frameworks.logging.rotate-ascii-logdir-leftover-log-rotation-stale-
[ 67%] scripts.base.frameworks.logging.rotate-ascii-logdir-leftover-log-rotation-stale-
[ 67%] scripts.base.frameworks.logging.rotate-default-logdir-leftover-log-rotation-shad
[ 67%] scripts.base.frameworks.logging.rotate-ascii-logdir-leftover-log-rotation-shadow
[ 67%] scripts.base.frameworks.logging.rotate-default-logdir-leftover-log-rotation-stal
[ 67%] scripts.base.frameworks.logging.rotate-default-logdir-leftover-log-rotation-stal
[ 67%] scripts.base.frameworks.logging.rotate-default-logdir-leftover-log-rotation-shad
[ 92%] scripts.policy.frameworks.files.deprecated-fields-concurrent-range-requests ... 
[ 98%] spicy.spicy-dump ... failed
1 of 1338 tests failed, 6 skipped
```

```
../../auxil/btest/btest -U spicy.spicy-dump
all 1 tests successful
```

```diff
diff --git a/testing/btest/Baseline/spicy.spicy-dump/output b/testing/btest/Baseline/spicy.spicy-dump/output
index 01a459395..01d632d28 100644
--- a/testing/btest/Baseline/spicy.spicy-dump/output
+++ b/testing/btest/Baseline/spicy.spicy-dump/output
@@ -1,4 +1,5 @@
 ### BTest baseline data generated by btest-diff. Do not edit. Use "btest -U/-u" to update. Requires BTest >= 0.63.
+ld: warning: -undefined dynamic_lookup may not work with chained fixups
 test::X {
   xs: [
     11
```

This doesn't seem like it's something desired, so I won't apply it. But, I'll drop the other items...

2022-11-01 01:25 UTC, jsoref commented
It looks like something automagically fixed up the commits as part of its magic, not quite sure which stage did it, but it seems reasonable.

2022-11-02 20:50 UTC, timwoj approved these changes
This looks good to me now. Can you squash it down to a single commit for merging? The docs submodule will need updating but there's an action that will take care of that.

2022-11-02 21:38 UTC, jsoref commented
@timwoj: done. Would you like to suggest the next little bit? This feels like roughly the right size for work...

2022-11-03 00:04 UTC, merged

2022-11-03 00:05 UTC, timwoj commented
> @timwoj: done. Would you like to suggest the next little bit? This feels like roughly the right size for work...

Changes in the src directory are fine but it's going to require going through with a fine-tooth comb during the review to make sure we're not breaking any sorts of APIs in the process.