Spelling src
zeek/zeek pull request #2544
Opened 2022-11-06 06:28 UTC by jsoref

Per https://github.com/zeek/zeek/pull/2503#issuecomment-1301507891

2022-11-07 19:05 UTC, timwoj requested changes
We clearly have problems with the word "overridden". Jeez.

I left quite a few comments on this one. The gist is that there are some functional changes here. I think some of them are ok but I'd like to pull those ones out into two separate PRs: one PR for functional changes (variable renaming) to .pac files and one of the others. I tried to mark what should go where. I did mark a couple of things that need to be reverted.

2022-11-07 20:23 UTC, jsoref commented on src/analyzer/protocol/smtp/SMTP.cc
> +	expect_recover = true;
Oops, should have caught that.

2022-11-09 15:36 UTC, timwoj approved these changes

2022-11-09 15:36 UTC, timwoj commented
Looks good now. Can you squash it down?

2022-11-11 19:49 UTC, merged