`export` extensions.
zeek/zeek pull request #3228
Opened 2023-08-11 10:42 UTC by rsmmr

Addresses #3218 and #3219 .

2023-08-14 12:01 UTC, bbannier requested changes

2023-08-16 08:26 UTC, bbannier commented on testing/btest/spicy/export-type-with-fields.zeek
> +export foo::X as foo::X4 without { x, y };
Interesting idea on the rename syntax, if we swapped the order this should even be possible as an extension of the original syntax in this PR, e.g.,

```zeek
export foo::X as foo::X3 with {
  a from x,
  b &log from z
};
```

This syntax doesn't require dropping `without`. I am still wondering whether the asymmetric attribute support will feel in practice, but I see your point about huge units (though there is also benefit in low-boilerplate explicitness).

2023-08-21 07:36 UTC, rsmmr commented on testing/btest/spicy/export-type-with-fields.zeek
> +export foo::X as foo::X4 without { x, y };
I'm with Jan here, `without` seems quite useful to have. It doesn't need to be fully symmetric IMO, I see it as a convenience shortcut. I also like the field renaming syntax `x as a`, would be easy to add (but not doing this now).

2023-08-21 07:39 UTC, rsmmr commented on src/spicy/spicyz/glue-compiler.cc
> +    }
Not sure about this. The code follows the other cases where the structs capture what the syntax provides, but don't interpret it further upfront. I'll rename `includes` to `with` and `excludes` to `without`, that should make it clearer.

2023-08-21 08:23 UTC, rsmmr commented on src/spicy/runtime-support.h
> +using RecordField = std::tuple<std::string, TypePtr, hilti::rt::Bool, hilti::rt::Bool>; // (ID, type, optional, &log)
Ack, I changing that in a new commit (but it doesn't work to use the same struct everywhere).

2023-08-21 08:42 UTC, bbannier approved these changes
🚀

2023-08-22 13:42 UTC, merged

2023-08-24 11:52 UTC, awelzel commented
Should this have a NEWS entry? It's a pretty nice enhancement.