generic-analyzer-fuzzer: Support NextPacket() fuzzing, too.
zeek/zeek pull request #3410
Opened 2023-10-26 11:07 UTC by awelzel

A number of analyzers that we've been fuzzing with the generic-analyzer-fuzzer setup do not implement DeliverStream() and instead only work with DeliverPacket() (ntp, syslog, sip, radius, ...). Calling DeliverStream() on those is pretty much a noop and fuzzing not effective.

This change adds support to fuzz DeliverPacket(). Whether to use packet or stream fuzzing is configured through a define via CMake.

This is still somewhat limited in that analyzers that support both, DeliverPacket() and DeliverStream(), only one path is fuzzed.

Closed #3398

2023-10-26 19:07 UTC, timwoj commented on src/fuzzers/generic-analyzer-fuzzer.cc
> +	Setup()
That definitely formatted weirdly.

2023-10-27 10:10 UTC, awelzel commented on src/fuzzers/CMakeLists.txt
> +add_generic_analyzer_fuzz_target(dhcp packet)
As in DM moving to tcp/udp. I'm naming the environment variable `_PROTO` instead of `_TYPE` so we can add another dimension later if wanted.

2023-10-27 16:05 UTC, timwoj requested changes

2023-10-27 16:05 UTC, timwoj commented on src/fuzzers/generic-analyzer-fuzzer.cc
> +static const char* FUZZ_ANALYZER_PROTO = TOSTRING(ZEEK_FUZZ_ANALYZER_PROTO);
How about `FUZZ_ANALYZER_TRANSPORT`? That's more concise.

2023-10-27 17:15 UTC, timwoj approved these changes

2023-10-27 17:20 UTC, merged

2023-10-30 19:24 UTC, timwoj commented
Since this was merged, coverage numbers reported by oss fuzz went from 49.07% to 49.57%. I expect they'll probably go up a bit more before stabilizing.