Perf fixes around FieldOffset() and ditch the EventMgr's flare
zeek/zeek pull request #3483
Opened 2023-12-03 15:01 UTC by awelzel

* The `FieldOffset()` one came up when drilling into `Conn::GetVal()` and `UpdateConnVal()` being slower than needed.
* The queue_flare has always been a thorn in my eye as sometimes its overhead is significant. Jan has raised this before, too. I think we can just get rid of it - see commit description.

2023-12-03 15:49 UTC, awelzel commented
The logging tests got a bunch faster, but these also [use recursive events for the log writes](https://github.com/zeek/zeek-benchmarker/blob/987b98b28a563978e973f6ac2cb59a412038fdc2/ci-based/scripts/microbenchmarks/logging/two-streams.zeek#L20-L22), so helps there a lot. Some of the pcaps "got maybe faster", but likely too much noise to tell confidently, hyperfine locally indicates yet.

![Screenshot from 2023-12-03 16-45-45](https://github.com/zeek/zeek/assets/2100509/4a1ec33c-6fb6-4f91-b07c-1bfef3704269)

2023-12-04 17:55 UTC, timwoj requested changes

2023-12-04 18:56 UTC, awelzel commented on src/analyzer/protocol/conn-size/ConnSize.cc
> +    assert(origidx >= 0);
Hmm, I was actually tempted to not even have the asserts. We're note consistent across the board around getting the filed offsets and just assume they are valid. Also, the involved types are so fundamental, if "connection" doesn't have "orig" and "resp", nothing really works anymore and the extra `internalWarning()`just extra cod.

How would dropping the assert sound? :-)

If you feel strongly, I'm happy to re-instantiate the, but will unlikely add such a warning in other places though or in the future. I could see a stronger helper that logs/aborts in the future.

2023-12-04 18:57 UTC, awelzel commented on src/Event.cc
> +    // the end of run_run after all of the sources have been processed
Eh, wanted to rename to `run_loop` but clearly didn't make it better.

2023-12-04 18:58 UTC, timwoj commented on src/analyzer/protocol/conn-size/ConnSize.cc
> +    assert(origidx >= 0);
I see what you mean about the inconsistency. I'm ok with just dropping the asserts.

2023-12-04 19:07 UTC, timwoj approved these changes

2023-12-05 15:49 UTC, merged