Squeeze a bit more performance out of the ends_with bif
zeek/zeek pull request #3554
Opened 2024-01-13 00:21 UTC by timwoj

Thanks to @JustinAzoff for pointing this one out and @awelzel for the possible optimized implementation. The previous implementation created two full std::string objects for every comparison, copying both strings every time. This avoids that by using string_view and only comparing the last part of the string to be searched.

```
Benchmark 1: ./src/zeek -b t.zeek
  Time (mean ± σ):     20.876 s ±  0.298 s    [User: 20.818 s, System: 0.060 s]
  Range (min … max):   20.408 s … 21.390 s    10 runs

Benchmark 2: ./src/zeek.new -b t.zeek
  Time (mean ± σ):     19.889 s ±  0.121 s    [User: 19.835 s, System: 0.057 s]
  Range (min … max):   19.654 s … 20.035 s    10 runs

Benchmark 3: ./src/zeek.rfind -b t.zeek
  Time (mean ± σ):     20.471 s ±  0.117 s    [User: 20.411 s, System: 0.062 s]
  Range (min … max):   20.226 s … 20.699 s    10 runs

Summary
  './src/zeek.new -b t.zeek' ran
    1.03 ± 0.01 times faster than './src/zeek.rfind -b t.zeek'
    1.05 ± 0.02 times faster than './src/zeek -b t.zeek'
```

Also included in the benchmark above is a version that uses `rfind` with string_views instead. It's still slower.

2024-01-13 01:14 UTC, ckreibich approved these changes
Since `StringVal` offers `ToStdStringView()` I'm pretty sure there are other `strings.bif` functions (that currently use `ToStdString()`) that allow that kind of optimization.

2024-01-13 10:20 UTC, awelzel requested changes

2024-01-13 10:20 UTC, awelzel commented on src/strings.bif
> +	auto s = std::string_view{str->CheckString() + str->Len() - sub->Len(),
Don't use `CheckString()` and instead  lso `ToStdStringView()`. `CheckString()` will 1) search the string for a `\0` from the beginning to the back for every invocation (most likely measurable impact for large strings) and 2) breaks `ends_with()` for Zeek strings with embedded '\0' characters due to replacing it with a placeholder string. It also tickles a reporter error message.

Suggest to add the following as a btest which works with Zeek 6.0 today:
```
# zeek -e 'print ends_with("a\x00\x00b", "\x00b")'
T
```

...

Hmm, `print "\x00" in "a\x00\x00b"` does tickle the reporter error and evaluates to `F`. From my view, there's nothing wrong with that and it should evaluate to `T`.

```
# zeek -e 'print "\x00" in "a\x00\x00b";'
error in <command line>, line 3: string with embedded NUL: "\x00"
F
```

Oh, and this is `T`, obviously :-)
```
# ZEEK_ALLOW_INIT_ERRORS=1 zeek -e 'print "aaa\x00bbb" in "<string-with-NUL>"'
error in <command line>, line 3: string with embedded NUL: "aaa\x00bbb"
T
```

2024-01-16 18:31 UTC, awelzel approved these changes
thanks for the fixup

2024-01-16 19:04 UTC, awelzel commented on testing/btest/bifs/string_utils.zeek
> +	print fmt("ends_with containing null: %d", ends_with("a\x00\x00b", "\x00b"));
Right, that's expected. But the `CheckString()` approach would've produced some (unexpected) stderr output.

2024-01-16 19:05 UTC, timwoj commented on testing/btest/bifs/string_utils.zeek
> +	print fmt("ends_with containing null: %d", ends_with("a\x00\x00b", "\x00b"));
Ah, I misunderstood then. No harm in adding it.

2024-01-16 19:07 UTC, merged