zeek.bif: Add find_in_zeekpath() helper
zeek/zeek pull request #3616
Opened 2024-02-21 16:22 UTC by awelzel

Relates to #3594. This helper can be used to determine the path that will be used by @load, if at all. Usage example:

    @if ( find_in_zeekpath("my-package") != "" )
    @load my-package
    @endif

Replaces #3615, renaming and

2024-02-21 19:08 UTC, timwoj requested changes

2024-02-21 19:08 UTC, timwoj commented on src/zeek.bif
> +## if neither can be found. Note that passing a relative path is an
Should this be "passing a relative or absolute path"? The if statement below is checking for a path starting with `/` and has a similar error message.

2024-02-21 19:08 UTC, timwoj commented on testing/btest/bifs/find_in_zeekpath.zeek
> +print "find_in_zeekpath pkg1.zeek", find_in_zeekpath("pkg1");
```suggestion
print "find_in_zeekpath pkg1.zeek", find_in_zeekpath("pkg1.zeek");
```

2024-02-22 01:25 UTC, JustinAzoff commented
I still like the idea of

```
@if ( can_load("the-package") )
@load the-package
@endif
```

Comparing the return value to "" seems a bit awkward.  Is there a use case where the resulting path is useful?

2024-02-22 08:25 UTC, awelzel commented
> Comparing the return value to "" seems a bit awkward. Is there a use case where the resulting path is useful?

Yeah, it would look better. It mostly came from the angle that `@load` also works for relative paths, too and a `can_load()` being over-promising here. As for the return value, my thought was the next possibly question would be what the actual path ended up being (could be interesting if your ZEEKPATH became very complex, or want to determine installation directories based on init-bare.zeek's location or some such tricks), so why not yield that instead.

I do agree that the new helper doesn't make the `can_load()` use-case obvious, but that also seemed relatively niche/advanced enough to allow for the `!= ""` awkwardness. If you/anyone feels much stronger, I'll add it.

> It's just needs a BiF - why not support both?

Given `find_in_zeekpath()`, `can_load()` seemed small enough to be provided by an external script. Though, not sure I understand your comment fully.

2024-02-26 18:29 UTC, timwoj approved these changes
:shipit:

2024-02-26 20:16 UTC, merged