Topic/awelzel/mysql amazing pp issue 2716 additions
zeek/zeek pull request #3816
Opened 2024-07-09 09:46 UTC by awelzel

Follow up for #3803

2024-07-11 14:18 UTC, AmazingPP requested changes
The additions in this PR are excellent. I noticed that the `BinaryTime` and `BinaryDate` records were not implemented in the PR, so I have written my own implementations for these records. Great work overall!

2024-07-11 14:18 UTC, AmazingPP commented on src/analyzer/protocol/mysql/mysql-protocol.pac
> +};
```suggestion
type Date = record {
	year : int16;
	month: int8;
	day  : int8;
};

type Time = record {
	hour  : int8;
	minute: int8;
	second: int8;
};

type BinaryDate = record {
	len: uint8 &enforce(len == 0 || len == 4 || len == 7 || len == 11);
	have_date: case ( len > 0 ) of {
		true  -> date  : Date;
		false -> none_1: empty;
	};
	have_time: case ( len > 4 ) of {
		true  -> time  : Time;
		false -> none_2: empty;
	};
	have_micros: case ( len > 7 ) of {
		true  -> micros: int32;
		false -> none_3: empty;
	};
};

type DurationTime = record {
	is_negative: int8 &enforce(is_negative == 0 || is_negative == 1);
	days       : int32;
	time       : Time;
};

type BinaryTime = record {
	len: uint8 &enforce(len == 0 || len == 8 || len == 12);
	have_time: case ( len > 0 ) of {
		true  -> time  : DurationTime;
		false -> none_1: empty;
	};
	have_micros: case ( len > 8 ) of {
		true  -> micros: int32;
		false -> none_2: empty;
	};
};
```

2024-07-12 09:02 UTC, awelzel commented on src/analyzer/protocol/mysql/mysql-protocol.pac
> +};
I'll take it :-) Thanks!

2024-07-13 02:06 UTC, AmazingPP approved these changes
LGTM

2024-07-25 00:42 UTC, timwoj approved these changes
Just a couple of minor nits. I didn't compare it to the protocol spec at all.

2024-07-25 00:42 UTC, timwoj commented on src/analyzer/protocol/mysql/mysql-protocol.pac
> +	auth_plugin_data_part_2_len = (auth_plugin_data_len > 8 && (auth_plugin_data_len - 8) > 13) ? auth_plugin_data_len - 8 : 13;
Wouldn't this be easier as `auth_plugin_data_len > 21` and a comment for the magic number?

2024-07-25 00:42 UTC, timwoj commented on src/analyzer/protocol/mysql/mysql-protocol.pac
> +		if ( auth_plugin_.length() > 0 && new_auth_plugin != auth_plugin_ )
I usually prefer to use `.empty()` vs comparing to zero.

2024-07-25 10:18 UTC, merged