Improve packet lag calculation
zeek/zeek pull request #3899
Opened 2024-08-26 10:56 UTC by J-Gras

Using network_time to calculate packet lag will produce wrong results when there is no packet available but network time does not (yet) fall back to wall clock. This introduces `get_current_packet_ts()`. For the BiF I thought about returning a record with an optional timestamp field that isn't set in case there is no packet. However, I wasn't sure it would be wort the effort.

2024-08-27 08:40 UTC, awelzel commented on src/zeek.bif
> +##      via :zeek:see:`event`, :zeek:see:`schedule` or by recipient of Broker
Hmm, yet, the user added is in `check_stats()` - that's a scheduled event, and the baselines verify the output of 0.0.

---

After looking a bit: `get_current_packet()` returns `pcap_packet` including timestamp information that should allow to build the timestamp in script land without a new BiF? I forget if there was another reason to have a separate BiF?

```

```

I think this comment could be relaxed, actually:

```
 ##      The return value of ``get_current_packet()`` further should be considered
 ##      undefined when called within event handlers raised via :zeek:see:`event`,
 ##      :zeek:see:`schedule` or by recipient of Broker messages.
```
`Packet::ToVal()` actually returns a zero-initialized structure if there wasn't a packet, I had missed that.

2024-10-29 14:24 UTC, awelzel commented on src/zeek.bif
> +##      via :zeek:see:`event`, :zeek:see:`schedule` or by recipient of Broker
Alternative proposal in DM was to add a BiF `get_packet_lag()` that handles it all internally.

2024-11-05 02:10 UTC, ckreibich requested changes
Sorrry for the delay here — do we actually document anywhere why & when Zeek updates network time to current time? It's mentioned in the NEWS, but without doing so, I think users will have a hard time understanding `network_time()` vs `get_current_packet_ts()`.

If you're on board with adding that, I'm (mildly) in favor of `get_current_packet_ts()`, mainly because we already have `get_current_packet_header()` (i.e., variations of retrieving packet info), and because it strikes me as potentially more useful to have in other settings than only having `get_packet_lag()`.

I'd then just add `get_packet_lag()` as a script-layer function — i.e., I see no harm in providing both. Hardly a lot of code. :-)

2024-12-10 11:42 UTC, J-Gras commented
I've added `get_packet_lag()` as a script-layer function and provided some more details in the doc-strings of the new functions 🙂

2024-12-10 17:23 UTC, awelzel approved these changes

2024-12-10 17:27 UTC, merged