Add pattern_end_offset to signature_state
zeek/zeek pull request #3908
Opened 2024-09-01 13:13 UTC by ronny8360988

Currently, when a signature is matched, a ```signature_match``` event is raised with the signature state, with the message and with the data as parameters, where ```data``` contains the whole payload of the last input chunk, and not just the matched payload.

This PR aims to add a ```pattern_end_offset``` field to ```signature_state```, such that ```signature_match``` events will have the context about the last offset within ```data``` in which the pattern is matched.

This field is optional, since not all signatures are matched against a pattern (i.e. pure rules).

2024-09-10 08:28 UTC, timwoj requested changes
This looks fine to me. The pre-commit CI build failing so that needs to be fixed. Can you squash it down to a single commit?

2024-10-10 13:46 UTC, ronny8360988 commented on src/RuleMatcher.cc
> +    state->match_end_offset = match_end_offset;
Great suggestion! Applying

2024-10-21 09:06 UTC, awelzel commented
I think this looks good now. Any chance you could provide a test, too? If not, I'm happy to create one during merge. I'd also squash all commits down.

One question/note:

> This PR aims to add a pattern_end_offset field to signature_state, such that signature_match events will have the context about the last offset within data in which the pattern is matched.

This isn't quite what you'll get. `data` is going to be the most recent packet data that was fed into the signature framework, but offset could be relative to the stream start  with e.g. TCP, so `offset` might end up larger than `|data|` and can't be used for indexing into `data`. The offset might still be useful to see how deep into a stream the match was, but it doesn't always help to determine the offset in `data`.

2024-10-27 11:51 UTC, eladsolomon-ms commented
> This isn't quite what you'll get. `data` is going to be the most recent packet data that was fed into the signature framework, but offset could be relative to the stream start with e.g. TCP, so `offset` might end up larger than `|data|` and can't be used for indexing into `data`. The offset might still be useful to see how deep into a stream the match was, but it doesn't always help to determine the offset in `data`.

WOW, you are totally correct!
What a bit oversight by us, thanks for pointing that out.

The intention here is to get the offset in `data`, for data extraction. How do you suggest we calculate that offset?

2024-10-28 18:15 UTC, awelzel commented
> The intention here is to get the offset in data, for data extraction. How do you suggest we calculate that offset?

Think we could keep the offset on the RuleEndpointState and then compute relative ones for the matches. I've fiddled with it in the following branch, also added a test with a match in the second TCP packet of a stream:

https://github.com/zeek/zeek/commit/0669aa4c2d7e454d9917c8946cc5eb7e100ed4d4

Robin also brought up adding offset as another parameter to `signature_match()` - that's a bit awkward due to custom event support and the optional `msg` we have now, but should be possible. I'll give it another try.

2024-10-30 13:47 UTC, awelzel commented
@ronny8360988 / @eladsolomon-ms - I'm going to close this PR, a compatible feature was added with #3996 .

The `signature_match()` event was extended to receive `end_of_match: count` which is relative to the beginning of `data`. This allows you to determine which part of `data` was still matched. Though, note that `data` only contains the current packet/payload, so anything matched in prior packets there's no visibility.

2024-10-30 13:47 UTC, closed without merging