Honor password logging
zeek/zeek pull request #3946
Opened 2024-09-19 16:54 UTC by martinvanhensbergen

The FTP policy allows adding extra commands to be logged, including the PASS command. When doing so, the actual plaintext password will be logged as argument of the command even though password_capture may be set to F.

With this change, if password capture is false, the password as part of the PASS argument will also be hidden.

2024-09-24 08:23 UTC, awelzel requested changes
Hey @martinvanhensbergen - thanks!

Have only nits - mind taking a look?

Would you be up for squashing some of the "Fix" commits before a merge? Otherwise can do so, too.

2024-09-24 08:23 UTC, awelzel commented on scripts/base/protocols/ftp/main.zeek
> +	if ( ! s$capture_password &&
You could condense to this to:
```
return ! s$capture_password && to_lower(s$user) !in guest_ids;
```

2024-09-24 08:23 UTC, awelzel commented on scripts/base/protocols/ftp/main.zeek
> +	local password_hidden_string:string = "<hidden>";
```suggestion
	local password_hidden_string = "<hidden>";
```

2024-09-24 08:23 UTC, awelzel commented on scripts/base/protocols/ftp/main.zeek
> +		 should_hide_password(s))
Suggest to use a single line and remove the braces. Also below.

2024-09-24 08:33 UTC, martinvanhensbergen commented
Hi @awelzel  thanks for reviewing and the suggested changes. I will make the changes and squash and cleanup a little later this week!

2024-09-27 13:11 UTC, martinvanhensbergen commented
Hi @awelzel 

I have applied the changes in the code as you suggested. I was wondering if squashing is necessary as i'd say this is done automatically by github on merge?

Regards
Martin

2024-09-27 13:15 UTC, awelzel commented
@martinvanhensbergen  - thanks!
> I have applied the changes in the code as you suggested. I was wondering if squashing is necessary as i'd say this is done automatically by github on merge?

We don't use the GitHub merge button :-) If you don't want to squash yourself, can also do during the merge by hand.

2024-09-27 13:18 UTC, martinvanhensbergen commented
If you would be able to do the merging & squash then that would be much appreciated ❤️ Thanks for the code suggestions though; it looks a bit cleaner indeed :)

2024-09-27 14:53 UTC, closed without merging

2024-09-27 14:54 UTC, awelzel commented
Merged with c36ae2f1a3e572676456dfb1230d776b9d0631bc.